# Generated by Django 4.2.3 on 2023-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_blogpage_blogtagindexpage_blogpagetag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': ('blog categories',), 'verbose_name_plural': 'blog categories'},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='a', help_text='A slug to identify posts by this category', max_length=255, verbose_name='slug'),
        ),
    ]
