# Generated by Django 4.2.3 on 2023-07-17 07:30

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_feed_image_blogpageauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='categories', to='blog.blogcategory'),
        ),
    ]
